# Wokwi Configuration File
# Reference: https://docs.wokwi.com/vscode/project-config
[wokwi]
version = 1
firmware = '../.pio/build/esp32-3248S035C/firmware.bin'
elf = '../.pio/build/esp32-3248S035C/firmware.elf'
